version: '3.8'

services:
  onlinelibrary_api:
    container_name: online_library_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${MANAGEMENT_PORT}:${MANAGEMENT_PORT}"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      MANAGEMENT_PORT: ${MANAGEMENT_PORT}
    depends_on:
      - onlinelibrary_db

  onlinelibrary_db:
    container_name: onlinelibrary_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  onlinelibrary_storage:
    container_name: online_library_storage
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=your_username
      - MINIO_ROOT_PASSWORD=your_pasword
      - MINIO_DEFAULT_BUCKETS=your_bucket_name

networks:
  minionetwork:
    driver: bridge
volumes:
  postgres_data:
  minio_data:
    driver: local
