server:
  port: ${SERVER_PORT:8080}
spring:
  profiles:
      active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: ${APP_NAME:onlinelibraryapi}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/onlinelibrary?useSSL=false&usePublicKeyRetrieval=true}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: false
  output:
    ansi:
      enabled: always
  servlet: 
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: ${SPRING_MAIL_PORT:1025}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:false}
            required: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED:false}

mail:
  from: ${MAIL_FROM:suport@onlinelibrary.com}
logging:
  file:
    name: ${LOG_FILE:app.log}
  



minio:
  url: ${MINIO_HOST:http://localhost:9000}
  access:
    name: ${MINIO_NAME:admin} 
    secret: ${MINIO_SECRET:adminadmin}
  bucket:
    name: ${BUCKET_NAME:onlinelibrary}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
  api-docs:
    path: /v3/api-docs
  packages-to-scan: br.com.rodrigo.onlinelibraryapi.controllers

management:
  server:
    port: ${MANAGEMENT_PORT:9090}
  endpoints:
    web:
      exposure:
        include: '*'
