spring:
  application:
    name: onlinelibraryapi
    port: 8000

  datasource:
    url: jdbc:postgresql://localhost:5432/onlinelibrary?useSSL=false&usePublicKeyRetrieval=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false

google:
  client-id: ${AUTH2_CLIENT_ID}
  client-secret: ${AUTH2_SECRET}
  redirect-uri: http://localhost:8080/api/v1/auth/google
server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
  api-docs:
    path: /v3/api-docs
  packages-to-scan: br.com.rodrigo.onlinelibraryapi.controllers
