spring:
  application:
    name: onlinelibraryapi
    port: 8000

  datasource:
    url: jdbc:postgresql://localhost:5432/onlinelibrary?useSSL=false&usePublicKeyRetrieval=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
logging:
  file:
    name: app.log
google:
  client-id: asdasdasdasd
  client-secret: asdasdasdasd
  redirect-uri: http://localhost:8080/api/v1/auth/google
server:
  port: 8080
output:
  ansi:
    enabled: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
  api-docs:
    path: /v3/api-docs
  packages-to-scan: br.com.rodrigo.onlinelibraryapi.controllers
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'


