spring:
  application:
    name: ${APP_NAME:onlinelibraryapi}
    port: ${APP_PORT:8000}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/onlinelibrary?useSSL=false&usePublicKeyRetrieval=true}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  output:
    ansi:
      enabled: always
logging:
  file:
    name: ${LOG_FILE:app.log}
  


server:
  port: ${SERVER_PORT:8080}

  

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
  api-docs:
    path: /v3/api-docs
  packages-to-scan: br.com.rodrigo.onlinelibraryapi.controllers

management:
  server:
    port: ${MANAGEMENT_PORT:9090}
  endpoints:
    web:
      exposure:
        include: '*'
