spring:
  application:
    name: onlinelibraryapi
    port: 8000

  datasource:
    url: jdbc:postgresql://localhost:5432/onlinelibrary?useSSL=false&usePublicKeyRetrieval=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${AUTH2_CLIENT_ID}
            client-secret: ${AUTH2_CLIENT_SECRET}

springdoc:
  swagger-ui:
    path: /docs.html
  api-docs:
    path: /docs
  packages-to-scan: br.com.rodrigo.onlinelibraryapi.controllers
