name: Online Library API Development Workflow
on: workflow_dispatch
jobs:
    firstJob:
        runs-on: ubuntu-latest
        steps:
            - name: Print greeting
              run: echo "Hello world!"
            - name: done job
              run: echo "Done - bye!"
             
